name: Run Shopify Scraper

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          response=$(curl -s https://yourproject.vercel.app/api/scrape)
          if [[ "$response" == *"Limit reached (1000 leads)"* ]]; then
            echo "Stopping GitHub Actions. Limit reached."
            exit 0
          fi
